### ISSUE TITLE
Possibly remove DIC

### ISSUE THREAD

**Issue by JeroenDeDauw** [SemanticMediaWiki/ExtensionManager#5]
@mwjames the state of this stuff is not as bad as I thought. The production code constructs stuff via `ServiceBuilder` and does not know about the DIC itself.

Still, I wonder if having the DIC is not overcomplicating things. This thing is not huge, and there are not dozens of devs working on it. So I'm thinking that some simple factories are all we need.

**Comment by mwjames** [comment]
> So I'm thinking that some simple factories are all we need.

Yeah this should be sufficient.

**Comment by JeroenDeDauw** [comment]
#6
